export enum LogType {
    NewPlayer = 'NewPlayer',
    SayMessage = 'SayMessage',
    CardReceived = 'CardReceived',
    CardTaken = 'CardTaken',
    Trade = 'Trade',
    CharacterCreated = 'CharacterCreated',
    CharacterDied = 'CharacterDied',
    CharacterStop = 'CharacterStop',
    AttackLost = 'AttackLost',
    AttackWon = 'AttackWon',
    AttackKill = 'AttackKill',
    AttackKilled = 'AttackKilled',
    Heal = 'Heal',
    Inspire = 'Inspire',
    PuzzleSolved = 'PuzzleSolved',
    PuzzleWrong = 'PuzzleWrong',
}