export enum LogType {
    NewPlayer = 'NewPlayer',
    SayMessage = 'SayMessage',
    CardReceived = 'CardReceived',
    CardTaken = 'CardTaken',
    Trade = 'Trade',
    CharacterCreated = 'CharacterCreated',
    CharacterDied = 'CharacterDied',
    CharacterStop = 'CharacterStop',
    Attack = 'Attack',
    Heal = 'Heal',
    Inspire = 'Inspire',
    PuzzleSolved = 'PuzzleSolved',
    PuzzleWrong = 'PuzzleWrong',
}